version: '3.8'

services:
  rest:
    container_name: memo-rest
    build:
      context: ./docker/golang
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./
        target: /go/src
    restart: always
    networks:
      - cros

  db:
    container_name: memo-db
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3309:3306
    env_file:
      - .env
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
    restart: always
    networks:
      - cros

volumes:
  mysql:

networks:
  cros:
    name: cros_network


