// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"memo/ent/likerecord"
	"memo/ent/memo"
	"memo/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// LikeRecordCreate is the builder for creating a LikeRecord entity.
type LikeRecordCreate struct {
	config
	mutation *LikeRecordMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (lrc *LikeRecordCreate) SetUserID(i int) *LikeRecordCreate {
	lrc.mutation.SetUserID(i)
	return lrc
}

// SetMemoID sets the "memo_id" field.
func (lrc *LikeRecordCreate) SetMemoID(u uuid.UUID) *LikeRecordCreate {
	lrc.mutation.SetMemoID(u)
	return lrc
}

// SetCreatedAt sets the "created_at" field.
func (lrc *LikeRecordCreate) SetCreatedAt(t time.Time) *LikeRecordCreate {
	lrc.mutation.SetCreatedAt(t)
	return lrc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (lrc *LikeRecordCreate) SetNillableCreatedAt(t *time.Time) *LikeRecordCreate {
	if t != nil {
		lrc.SetCreatedAt(*t)
	}
	return lrc
}

// AddMemoIDs adds the "memos" edge to the Memo entity by IDs.
func (lrc *LikeRecordCreate) AddMemoIDs(ids ...uuid.UUID) *LikeRecordCreate {
	lrc.mutation.AddMemoIDs(ids...)
	return lrc
}

// AddMemos adds the "memos" edges to the Memo entity.
func (lrc *LikeRecordCreate) AddMemos(m ...*Memo) *LikeRecordCreate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return lrc.AddMemoIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (lrc *LikeRecordCreate) AddUserIDs(ids ...int) *LikeRecordCreate {
	lrc.mutation.AddUserIDs(ids...)
	return lrc
}

// AddUsers adds the "users" edges to the User entity.
func (lrc *LikeRecordCreate) AddUsers(u ...*User) *LikeRecordCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return lrc.AddUserIDs(ids...)
}

// Mutation returns the LikeRecordMutation object of the builder.
func (lrc *LikeRecordCreate) Mutation() *LikeRecordMutation {
	return lrc.mutation
}

// Save creates the LikeRecord in the database.
func (lrc *LikeRecordCreate) Save(ctx context.Context) (*LikeRecord, error) {
	lrc.defaults()
	return withHooks(ctx, lrc.sqlSave, lrc.mutation, lrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lrc *LikeRecordCreate) SaveX(ctx context.Context) *LikeRecord {
	v, err := lrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lrc *LikeRecordCreate) Exec(ctx context.Context) error {
	_, err := lrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lrc *LikeRecordCreate) ExecX(ctx context.Context) {
	if err := lrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lrc *LikeRecordCreate) defaults() {
	if _, ok := lrc.mutation.CreatedAt(); !ok {
		v := likerecord.DefaultCreatedAt()
		lrc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lrc *LikeRecordCreate) check() error {
	if _, ok := lrc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LikeRecord.user_id"`)}
	}
	if _, ok := lrc.mutation.MemoID(); !ok {
		return &ValidationError{Name: "memo_id", err: errors.New(`ent: missing required field "LikeRecord.memo_id"`)}
	}
	if _, ok := lrc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LikeRecord.created_at"`)}
	}
	return nil
}

func (lrc *LikeRecordCreate) sqlSave(ctx context.Context) (*LikeRecord, error) {
	if err := lrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	lrc.mutation.id = &_node.ID
	lrc.mutation.done = true
	return _node, nil
}

func (lrc *LikeRecordCreate) createSpec() (*LikeRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &LikeRecord{config: lrc.config}
		_spec = sqlgraph.NewCreateSpec(likerecord.Table, sqlgraph.NewFieldSpec(likerecord.FieldID, field.TypeInt))
	)
	if value, ok := lrc.mutation.UserID(); ok {
		_spec.SetField(likerecord.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := lrc.mutation.MemoID(); ok {
		_spec.SetField(likerecord.FieldMemoID, field.TypeUUID, value)
		_node.MemoID = value
	}
	if value, ok := lrc.mutation.CreatedAt(); ok {
		_spec.SetField(likerecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := lrc.mutation.MemosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   likerecord.MemosTable,
			Columns: []string{likerecord.MemosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memo.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := lrc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   likerecord.UsersTable,
			Columns: []string{likerecord.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LikeRecordCreateBulk is the builder for creating many LikeRecord entities in bulk.
type LikeRecordCreateBulk struct {
	config
	builders []*LikeRecordCreate
}

// Save creates the LikeRecord entities in the database.
func (lrcb *LikeRecordCreateBulk) Save(ctx context.Context) ([]*LikeRecord, error) {
	specs := make([]*sqlgraph.CreateSpec, len(lrcb.builders))
	nodes := make([]*LikeRecord, len(lrcb.builders))
	mutators := make([]Mutator, len(lrcb.builders))
	for i := range lrcb.builders {
		func(i int, root context.Context) {
			builder := lrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LikeRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lrcb *LikeRecordCreateBulk) SaveX(ctx context.Context) []*LikeRecord {
	v, err := lrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lrcb *LikeRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := lrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lrcb *LikeRecordCreateBulk) ExecX(ctx context.Context) {
	if err := lrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
