// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"memo/ent/likerecord"
	"memo/ent/memo"
	"memo/ent/predicate"
	"memo/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LikeRecordQuery is the builder for querying LikeRecord entities.
type LikeRecordQuery struct {
	config
	ctx        *QueryContext
	order      []likerecord.OrderOption
	inters     []Interceptor
	predicates []predicate.LikeRecord
	withMemos  *MemoQuery
	withUsers  *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LikeRecordQuery builder.
func (lrq *LikeRecordQuery) Where(ps ...predicate.LikeRecord) *LikeRecordQuery {
	lrq.predicates = append(lrq.predicates, ps...)
	return lrq
}

// Limit the number of records to be returned by this query.
func (lrq *LikeRecordQuery) Limit(limit int) *LikeRecordQuery {
	lrq.ctx.Limit = &limit
	return lrq
}

// Offset to start from.
func (lrq *LikeRecordQuery) Offset(offset int) *LikeRecordQuery {
	lrq.ctx.Offset = &offset
	return lrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lrq *LikeRecordQuery) Unique(unique bool) *LikeRecordQuery {
	lrq.ctx.Unique = &unique
	return lrq
}

// Order specifies how the records should be ordered.
func (lrq *LikeRecordQuery) Order(o ...likerecord.OrderOption) *LikeRecordQuery {
	lrq.order = append(lrq.order, o...)
	return lrq
}

// QueryMemos chains the current query on the "memos" edge.
func (lrq *LikeRecordQuery) QueryMemos() *MemoQuery {
	query := (&MemoClient{config: lrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(likerecord.Table, likerecord.FieldID, selector),
			sqlgraph.To(memo.Table, memo.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, likerecord.MemosTable, likerecord.MemosColumn),
		)
		fromU = sqlgraph.SetNeighbors(lrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsers chains the current query on the "users" edge.
func (lrq *LikeRecordQuery) QueryUsers() *UserQuery {
	query := (&UserClient{config: lrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(likerecord.Table, likerecord.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, likerecord.UsersTable, likerecord.UsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(lrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LikeRecord entity from the query.
// Returns a *NotFoundError when no LikeRecord was found.
func (lrq *LikeRecordQuery) First(ctx context.Context) (*LikeRecord, error) {
	nodes, err := lrq.Limit(1).All(setContextOp(ctx, lrq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{likerecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lrq *LikeRecordQuery) FirstX(ctx context.Context) *LikeRecord {
	node, err := lrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LikeRecord ID from the query.
// Returns a *NotFoundError when no LikeRecord ID was found.
func (lrq *LikeRecordQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lrq.Limit(1).IDs(setContextOp(ctx, lrq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{likerecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lrq *LikeRecordQuery) FirstIDX(ctx context.Context) int {
	id, err := lrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LikeRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LikeRecord entity is found.
// Returns a *NotFoundError when no LikeRecord entities are found.
func (lrq *LikeRecordQuery) Only(ctx context.Context) (*LikeRecord, error) {
	nodes, err := lrq.Limit(2).All(setContextOp(ctx, lrq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{likerecord.Label}
	default:
		return nil, &NotSingularError{likerecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lrq *LikeRecordQuery) OnlyX(ctx context.Context) *LikeRecord {
	node, err := lrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LikeRecord ID in the query.
// Returns a *NotSingularError when more than one LikeRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (lrq *LikeRecordQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lrq.Limit(2).IDs(setContextOp(ctx, lrq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{likerecord.Label}
	default:
		err = &NotSingularError{likerecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lrq *LikeRecordQuery) OnlyIDX(ctx context.Context) int {
	id, err := lrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LikeRecords.
func (lrq *LikeRecordQuery) All(ctx context.Context) ([]*LikeRecord, error) {
	ctx = setContextOp(ctx, lrq.ctx, "All")
	if err := lrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LikeRecord, *LikeRecordQuery]()
	return withInterceptors[[]*LikeRecord](ctx, lrq, qr, lrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lrq *LikeRecordQuery) AllX(ctx context.Context) []*LikeRecord {
	nodes, err := lrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LikeRecord IDs.
func (lrq *LikeRecordQuery) IDs(ctx context.Context) (ids []int, err error) {
	if lrq.ctx.Unique == nil && lrq.path != nil {
		lrq.Unique(true)
	}
	ctx = setContextOp(ctx, lrq.ctx, "IDs")
	if err = lrq.Select(likerecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lrq *LikeRecordQuery) IDsX(ctx context.Context) []int {
	ids, err := lrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lrq *LikeRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lrq.ctx, "Count")
	if err := lrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lrq, querierCount[*LikeRecordQuery](), lrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lrq *LikeRecordQuery) CountX(ctx context.Context) int {
	count, err := lrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lrq *LikeRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lrq.ctx, "Exist")
	switch _, err := lrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lrq *LikeRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := lrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LikeRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lrq *LikeRecordQuery) Clone() *LikeRecordQuery {
	if lrq == nil {
		return nil
	}
	return &LikeRecordQuery{
		config:     lrq.config,
		ctx:        lrq.ctx.Clone(),
		order:      append([]likerecord.OrderOption{}, lrq.order...),
		inters:     append([]Interceptor{}, lrq.inters...),
		predicates: append([]predicate.LikeRecord{}, lrq.predicates...),
		withMemos:  lrq.withMemos.Clone(),
		withUsers:  lrq.withUsers.Clone(),
		// clone intermediate query.
		sql:  lrq.sql.Clone(),
		path: lrq.path,
	}
}

// WithMemos tells the query-builder to eager-load the nodes that are connected to
// the "memos" edge. The optional arguments are used to configure the query builder of the edge.
func (lrq *LikeRecordQuery) WithMemos(opts ...func(*MemoQuery)) *LikeRecordQuery {
	query := (&MemoClient{config: lrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lrq.withMemos = query
	return lrq
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "users" edge. The optional arguments are used to configure the query builder of the edge.
func (lrq *LikeRecordQuery) WithUsers(opts ...func(*UserQuery)) *LikeRecordQuery {
	query := (&UserClient{config: lrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lrq.withUsers = query
	return lrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LikeRecord.Query().
//		GroupBy(likerecord.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lrq *LikeRecordQuery) GroupBy(field string, fields ...string) *LikeRecordGroupBy {
	lrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LikeRecordGroupBy{build: lrq}
	grbuild.flds = &lrq.ctx.Fields
	grbuild.label = likerecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.LikeRecord.Query().
//		Select(likerecord.FieldUserID).
//		Scan(ctx, &v)
func (lrq *LikeRecordQuery) Select(fields ...string) *LikeRecordSelect {
	lrq.ctx.Fields = append(lrq.ctx.Fields, fields...)
	sbuild := &LikeRecordSelect{LikeRecordQuery: lrq}
	sbuild.label = likerecord.Label
	sbuild.flds, sbuild.scan = &lrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LikeRecordSelect configured with the given aggregations.
func (lrq *LikeRecordQuery) Aggregate(fns ...AggregateFunc) *LikeRecordSelect {
	return lrq.Select().Aggregate(fns...)
}

func (lrq *LikeRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lrq); err != nil {
				return err
			}
		}
	}
	for _, f := range lrq.ctx.Fields {
		if !likerecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lrq.path != nil {
		prev, err := lrq.path(ctx)
		if err != nil {
			return err
		}
		lrq.sql = prev
	}
	return nil
}

func (lrq *LikeRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LikeRecord, error) {
	var (
		nodes       = []*LikeRecord{}
		_spec       = lrq.querySpec()
		loadedTypes = [2]bool{
			lrq.withMemos != nil,
			lrq.withUsers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LikeRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LikeRecord{config: lrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lrq.withMemos; query != nil {
		if err := lrq.loadMemos(ctx, query, nodes,
			func(n *LikeRecord) { n.Edges.Memos = []*Memo{} },
			func(n *LikeRecord, e *Memo) { n.Edges.Memos = append(n.Edges.Memos, e) }); err != nil {
			return nil, err
		}
	}
	if query := lrq.withUsers; query != nil {
		if err := lrq.loadUsers(ctx, query, nodes,
			func(n *LikeRecord) { n.Edges.Users = []*User{} },
			func(n *LikeRecord, e *User) { n.Edges.Users = append(n.Edges.Users, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lrq *LikeRecordQuery) loadMemos(ctx context.Context, query *MemoQuery, nodes []*LikeRecord, init func(*LikeRecord), assign func(*LikeRecord, *Memo)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*LikeRecord)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Memo(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(likerecord.MemosColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.like_record_memos
		if fk == nil {
			return fmt.Errorf(`foreign-key "like_record_memos" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "like_record_memos" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (lrq *LikeRecordQuery) loadUsers(ctx context.Context, query *UserQuery, nodes []*LikeRecord, init func(*LikeRecord), assign func(*LikeRecord, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*LikeRecord)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(likerecord.UsersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.like_record_users
		if fk == nil {
			return fmt.Errorf(`foreign-key "like_record_users" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "like_record_users" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (lrq *LikeRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lrq.querySpec()
	_spec.Node.Columns = lrq.ctx.Fields
	if len(lrq.ctx.Fields) > 0 {
		_spec.Unique = lrq.ctx.Unique != nil && *lrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lrq.driver, _spec)
}

func (lrq *LikeRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(likerecord.Table, likerecord.Columns, sqlgraph.NewFieldSpec(likerecord.FieldID, field.TypeInt))
	_spec.From = lrq.sql
	if unique := lrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lrq.path != nil {
		_spec.Unique = true
	}
	if fields := lrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, likerecord.FieldID)
		for i := range fields {
			if fields[i] != likerecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lrq *LikeRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lrq.driver.Dialect())
	t1 := builder.Table(likerecord.Table)
	columns := lrq.ctx.Fields
	if len(columns) == 0 {
		columns = likerecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lrq.sql != nil {
		selector = lrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lrq.ctx.Unique != nil && *lrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lrq.predicates {
		p(selector)
	}
	for _, p := range lrq.order {
		p(selector)
	}
	if offset := lrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LikeRecordGroupBy is the group-by builder for LikeRecord entities.
type LikeRecordGroupBy struct {
	selector
	build *LikeRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lrgb *LikeRecordGroupBy) Aggregate(fns ...AggregateFunc) *LikeRecordGroupBy {
	lrgb.fns = append(lrgb.fns, fns...)
	return lrgb
}

// Scan applies the selector query and scans the result into the given value.
func (lrgb *LikeRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lrgb.build.ctx, "GroupBy")
	if err := lrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LikeRecordQuery, *LikeRecordGroupBy](ctx, lrgb.build, lrgb, lrgb.build.inters, v)
}

func (lrgb *LikeRecordGroupBy) sqlScan(ctx context.Context, root *LikeRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lrgb.fns))
	for _, fn := range lrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lrgb.flds)+len(lrgb.fns))
		for _, f := range *lrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LikeRecordSelect is the builder for selecting fields of LikeRecord entities.
type LikeRecordSelect struct {
	*LikeRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lrs *LikeRecordSelect) Aggregate(fns ...AggregateFunc) *LikeRecordSelect {
	lrs.fns = append(lrs.fns, fns...)
	return lrs
}

// Scan applies the selector query and scans the result into the given value.
func (lrs *LikeRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lrs.ctx, "Select")
	if err := lrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LikeRecordQuery, *LikeRecordSelect](ctx, lrs.LikeRecordQuery, lrs, lrs.inters, v)
}

func (lrs *LikeRecordSelect) sqlScan(ctx context.Context, root *LikeRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lrs.fns))
	for _, fn := range lrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
