// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"memo/ent/likerecord"
	"memo/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LikeRecordDelete is the builder for deleting a LikeRecord entity.
type LikeRecordDelete struct {
	config
	hooks    []Hook
	mutation *LikeRecordMutation
}

// Where appends a list predicates to the LikeRecordDelete builder.
func (lrd *LikeRecordDelete) Where(ps ...predicate.LikeRecord) *LikeRecordDelete {
	lrd.mutation.Where(ps...)
	return lrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lrd *LikeRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, lrd.sqlExec, lrd.mutation, lrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (lrd *LikeRecordDelete) ExecX(ctx context.Context) int {
	n, err := lrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lrd *LikeRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(likerecord.Table, sqlgraph.NewFieldSpec(likerecord.FieldID, field.TypeInt))
	if ps := lrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	lrd.mutation.done = true
	return affected, err
}

// LikeRecordDeleteOne is the builder for deleting a single LikeRecord entity.
type LikeRecordDeleteOne struct {
	lrd *LikeRecordDelete
}

// Where appends a list predicates to the LikeRecordDelete builder.
func (lrdo *LikeRecordDeleteOne) Where(ps ...predicate.LikeRecord) *LikeRecordDeleteOne {
	lrdo.lrd.mutation.Where(ps...)
	return lrdo
}

// Exec executes the deletion query.
func (lrdo *LikeRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := lrdo.lrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{likerecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lrdo *LikeRecordDeleteOne) ExecX(ctx context.Context) {
	if err := lrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
