// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"memo/ent/memo"
	"memo/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MemoCreate is the builder for creating a Memo entity.
type MemoCreate struct {
	config
	mutation *MemoMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (mc *MemoCreate) SetUserID(i int) *MemoCreate {
	mc.mutation.SetUserID(i)
	return mc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (mc *MemoCreate) SetNillableUserID(i *int) *MemoCreate {
	if i != nil {
		mc.SetUserID(*i)
	}
	return mc
}

// SetDescription sets the "description" field.
func (mc *MemoCreate) SetDescription(s string) *MemoCreate {
	mc.mutation.SetDescription(s)
	return mc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (mc *MemoCreate) SetNillableDescription(s *string) *MemoCreate {
	if s != nil {
		mc.SetDescription(*s)
	}
	return mc
}

// SetUpdatedAt sets the "updated_at" field.
func (mc *MemoCreate) SetUpdatedAt(t time.Time) *MemoCreate {
	mc.mutation.SetUpdatedAt(t)
	return mc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mc *MemoCreate) SetNillableUpdatedAt(t *time.Time) *MemoCreate {
	if t != nil {
		mc.SetUpdatedAt(*t)
	}
	return mc
}

// SetCreatedAt sets the "created_at" field.
func (mc *MemoCreate) SetCreatedAt(t time.Time) *MemoCreate {
	mc.mutation.SetCreatedAt(t)
	return mc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mc *MemoCreate) SetNillableCreatedAt(t *time.Time) *MemoCreate {
	if t != nil {
		mc.SetCreatedAt(*t)
	}
	return mc
}

// SetID sets the "id" field.
func (mc *MemoCreate) SetID(u uuid.UUID) *MemoCreate {
	mc.mutation.SetID(u)
	return mc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mc *MemoCreate) SetNillableID(u *uuid.UUID) *MemoCreate {
	if u != nil {
		mc.SetID(*u)
	}
	return mc
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (mc *MemoCreate) AddUserIDs(ids ...int) *MemoCreate {
	mc.mutation.AddUserIDs(ids...)
	return mc
}

// AddUsers adds the "users" edges to the User entity.
func (mc *MemoCreate) AddUsers(u ...*User) *MemoCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return mc.AddUserIDs(ids...)
}

// Mutation returns the MemoMutation object of the builder.
func (mc *MemoCreate) Mutation() *MemoMutation {
	return mc.mutation
}

// Save creates the Memo in the database.
func (mc *MemoCreate) Save(ctx context.Context) (*Memo, error) {
	mc.defaults()
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MemoCreate) SaveX(ctx context.Context) *Memo {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MemoCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MemoCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MemoCreate) defaults() {
	if _, ok := mc.mutation.Description(); !ok {
		v := memo.DefaultDescription
		mc.mutation.SetDescription(v)
	}
	if _, ok := mc.mutation.UpdatedAt(); !ok {
		v := memo.DefaultUpdatedAt()
		mc.mutation.SetUpdatedAt(v)
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		v := memo.DefaultCreatedAt()
		mc.mutation.SetCreatedAt(v)
	}
	if _, ok := mc.mutation.ID(); !ok {
		v := memo.DefaultID()
		mc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MemoCreate) check() error {
	if _, ok := mc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Memo.description"`)}
	}
	if _, ok := mc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Memo.updated_at"`)}
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Memo.created_at"`)}
	}
	return nil
}

func (mc *MemoCreate) sqlSave(ctx context.Context) (*Memo, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MemoCreate) createSpec() (*Memo, *sqlgraph.CreateSpec) {
	var (
		_node = &Memo{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(memo.Table, sqlgraph.NewFieldSpec(memo.FieldID, field.TypeUUID))
	)
	if id, ok := mc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mc.mutation.UserID(); ok {
		_spec.SetField(memo.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := mc.mutation.Description(); ok {
		_spec.SetField(memo.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := mc.mutation.UpdatedAt(); ok {
		_spec.SetField(memo.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := mc.mutation.CreatedAt(); ok {
		_spec.SetField(memo.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := mc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memo.UsersTable,
			Columns: []string{memo.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemoCreateBulk is the builder for creating many Memo entities in bulk.
type MemoCreateBulk struct {
	config
	builders []*MemoCreate
}

// Save creates the Memo entities in the database.
func (mcb *MemoCreateBulk) Save(ctx context.Context) ([]*Memo, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Memo, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MemoCreateBulk) SaveX(ctx context.Context) []*Memo {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MemoCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MemoCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
