// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LikeRecord is the predicate function for likerecord builders.
type LikeRecord func(*sql.Selector)

// Memo is the predicate function for memo builders.
type Memo func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
